-- AlterTable
ALTER TABLE `orderitems` MODIFY `status` ENUM('IDLE', 'NOT_REQUIRED', 'IN_KITCHEN', 'SERVED', 'COMPLETED') NOT NULL DEFAULT 'IDLE';

-- AlterTable
ALTER TABLE `orders` MODIFY `kitchenStatus` ENUM('IDLE', 'NOT_REQUIRED', 'IN_KITCHEN', 'SERVED', 'COMPLETED') NOT NULL DEFAULT 'IDLE';
